### ISSUE TITLE
Update tests in template project

### ISSUE THREAD

**Issue by michael-vansickle** [dojo/cli-create-app#100]
tests/unit/App.ts creates a spy for the `setProperties` function of the `HelloWorld` class. This method has been renamed `__setProperties__` and, as a result, the created test suite fails to create the spy.

**Comment by kitsonk** [comment]
We should revisit the tests as a whole, related to #83 instead of fixing what would actually be an anti-pattern.

I would recommend just doing #83 and cleaning the whole mess up.

**Comment by kitsonk** [comment]
Nevermind, we already merged #101.

We need to mention issues in the commit messages so the issue get closed properly when we merge them.
