### ISSUE TITLE
Enable tsx support by default

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-create-app#102]
**Enhancement**

The template application should have tsx enabled by default in line with the `tsconfig.json` in the examples:

https://github.com/dojo/examples/blob/a386aa2332ea37c29f33c329ff5254322f33c511/todo-mvc-tsx/tsconfig.json#L5-L6

**Comment by agubler** [comment]
Resolved by https://github.com/dojo/cli-create-app/pull/104
