### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [dojo/cli-create-app#130]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by matt-gadd** [comment]
Thanks for raising the issue, but we’re happy with ejs, it’s stable and it’s license is clearly stated/transparent. The templating in cli-create-app is not performance critical either.

**Comment by Drulac** [comment]
I had forgot to add a licence, so I just added GNU General Public License v3.0
