### ISSUE TITLE
Readme review

### ISSUE THREAD

**Issue by tomdye** [dojo/cli-create-app#139]
- summary
   - `The create app command for the dojo cli` -> `The create app command for @dojo/cli`
- features
   - installed build command is `cli-build-app`, not `cli-build-webpack`
   - start app running `dojo build --mode dev --watch memory --serve`
   - build tests with `dojo build --mode test`, they're built to `output/test`
   - `dojo build` creates `output/dist`

**question?**
Do we want to include this in the `features` as we already have the above info in the newly created app's readme?

**Comment by edhager** [comment]
- Remove the WARNING
- "All the dependencies have been pre-installed using" change to "All the dependencies are pre-installed using"
