### ISSUE TITLE
Provide self contained npm scripts

### ISSUE THREAD

**Issue by aciccarello** [dojo/cli-create-app#154]
## Enhancement 
Dojo CLI applications should be easy to run. npm scripts are easy for people to use who may not be familiar with the Dojo CLI and can run dev dependencies that don't need to be installed separately (i.e. globally)

### Expected behavior:
An application generated using cli-create-app should be able to be installed an run easily when git cloned. Ideally, some npm scripts should be runnable immediately after install.

### Actual behavior:
A cloned repo generated from the cil-create-app requires the domo cli to be installed to run.

### Current template
https://github.com/dojo/cli-create-app/blob/fbd9118d30ee7a7d6483d6ed5814e231e331d441/src/templates/package.json#L1-L14

### Suggested Template
```json
{
  "name": "<%- appName %>",
  "version": "1.0.0",
  "scripts": {
    "dev": "dojo build --mode dev --watch memory --serve",
    "build": "dojo build",
    "test": "dojo build -m test && dojo test -a"
  },
  "dependencies": {
    "@dojo/framework": "~3.0.0",
    "tslib": "~1.8.1"
  },
  "devDependencies": {
    "@dojo/cli": "^3.0.0",
    "@dojo/cli-build-app": "~3.0.0",
    "@dojo/cli-test-intern": "~3.0.0",
    "@types/node": "~9.6.5",
    "typescript": "~2.6.1"
  }
}
```

**Comment by KaneFreeman** [comment]
Since `--watch memory` has a few issues, the dev script really should just be `dojo build -m dev -w -s`.

Also, since `--mode test` is depreciated, what do you think of the following as a replacement?
```javascript
    "test": "npm run test:unit && npm run test:functional",
    "test:unit": "dojo build -m unit && dojo test -u",
    "test:functional": "dojo build -m functional && dojo test -f"
```
