### ISSUE TITLE
Page layout not correct when I update to dojo 5.0.0

### ISSUE THREAD

**Issue by xiaohulu** [dojo/cli-create-app#164]
I update my `cli` and `cli-create-app` to `5.0.0`, then I use `dojo create app --name myApp` create a dojo app, then run in dev mode. But the “Home”,"About" and "PROFILE" displayed at the left, not displayed at right.

I can not upload image to “github.com”.

**Comment by agubler** [comment]
@xiaohulu Thank you for raising an issue. I have just created a new application with 5.0.0, built in dev mode and the menu items are displayed on the right as expected.

Can you provide some more information, for example operating system, node versions, npm version?

**Comment by xiaohulu** [comment]
```
windows 10
node v10.15.0
npm 6.4.1
```

**Comment by xiaohulu** [comment]
warn node unsupported
```
- [3/9] Installing through2@^2.0.0
WARN node unsupported "node@v10.15.0" is incompatible with @dojo/cli-build-app@5.0.0 › @dojo/webpack-contrib@5.0.0 › filter-css@0.1.2 › update-notifier@0.7.0 › latest-version@2.0.0 › package-json@2.4.0 › got@^5.0.0, expected node@>=0.10.0 <7
- [5/9] Installing typescript@~2.6.1platform unsupported @dojo/cli-build-app@5.0.0 › compression-webpack-plugin@2.0.0 › webpack@4.25.1 › watchpack@1.6.0 › chokidar@2.0.4 › fsevents@^1.2.2 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.2.2] optional install error: Package require os(darwin) not compatible with your platform(win32)
√ Installed 9 packages
√ Linked 1074 latest versions
```

**Comment by agubler** [comment]
@xiaohulu I think that warning is coming from a dependency somewhere, but shouldn't be an issue.

We've tried a new cli-create-app built in dev mode, on windows and mac and can't seem to reproduce the issue described.

**Comment by xiaohulu** [comment]
Ok, thanks.

**Comment by xiaohulu** [comment]
When I run `npm install` print below erros
```
E:\source\client>npm install
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-01-31T12_51_15_704Z-debug.log
```

Maybe it was my network problem.

**Comment by xiaohulu** [comment]
@agubler 

I just now use dojo 4 to create a dojo app, then run in dev mode, It display correct.

I use `npm run build` to build a dist version, and I upload the dist to https://github.com/xiaohulu/dojo5-dist repo.

the release version's page also display not correct.

I hope the dojo5-dist repo can help you find what i missed

**Comment by agubler** [comment]
@xiaohulu I can see the issue when running your built output but I am yet to be able to reproduce it 😢 

Will continue looking into this for you. Are there any other details you can think of that might help track down the problem?

Also just to be sure could please print out the dojo cli version details using `dojo version`?

Thanks!

**Comment by xiaohulu** [comment]
My dojo version is

```sh
C:\Users\Administrator\blocklang>dojo version

You are currently running @dojo/cli@5.0.0

The currently installed commands are:

  ▹  @dojo/cli-build-app@5.0.0
  ▹  @dojo/cli-create-app@5.0.0
  ▹  @dojo/cli-test-intern@5.0.0
```

**Comment by xiaohulu** [comment]
it was my network problem, missing some dependencies.
