### ISSUE TITLE
Update dependencies of created app

### ISSUE THREAD

**Issue by dylans** [dojo/cli-create-app#39]
In working through the tutorials, we should make sure we're keeping the generated app current, specifically the versions of intern, remap-istanbul, the version of ts (in both package.json and tsconfig.json, which by the way are not the same at the moment, one is 2.1.4 and the other is 2.0.3), and remove extra-rxjs from typings.json.

**Comment by agubler** [comment]
@dylans `extra-rxjs` has been removed from the templates that generate the app - it is however inconsistent between the ts version in the template `tsconfig.json` and `package.json` though (we should just remove the version from the `tsconfig.json` imo).

I think there might be an issue with upgrading the version of `intern` regarding the type changes it requires (i had issues doing it for examples/todo-mvc) - we get round this internally by having `dev` / `dist` typings pipelines which we do not have for the consumer (they just do a `typings install`)

**Comment by agubler** [comment]
I think this has been completed.
