### ISSUE TITLE
Include meta files in app template?

### ISSUE THREAD

**Issue by agubler** [dojo/cli-create-app#45]
Is it worthwhile adding meta files such as `.gitignore` to the app template?

**Comment by dylans** [comment]
I would say yes, anything to make it easier for someone to get started without having to figure out all of the tedious steps to getting their code into git, the better.

**Comment by agubler** [comment]
Are there any other meta files we should add by default? I am planning on adding a `.gitignore`, any other suggestions welcome.

**Comment by agubler** [comment]
Perhaps a template `README.md`
