### ISSUE TITLE
Add comments to created app code, or link to a turorial

### ISSUE THREAD

**Issue by rishson** [dojo/cli-create-app#58]
The code produced has no comments. If a new user runs `create` then I think the code generated should be very explicit in its intentions, e.g.

```
const classes = this.classes(
  css.hello,
  this.properties.stranger ? css.upsidedown : null
);
```

might be better written as:

```
// always apply the 'hello' class
const classesToApply = this.classes(css.hello);

// if stranger is true, then also apply the upsidedown class from our css
if( this.properties.stranger) {
  classesToApply.push(css.upsidedown);
}
```
We can either add add comments to the generated code, or we could write a tutorial that explains the generated code, and keep it in sync with any changes to this repo. The advantage of the tutorial approach is that the generated code would also work well for experienced users.

**Comment by kitsonk** [comment]
Agreed that the scaffolded app should have useful comments and be generally well documented.
