### ISSUE TITLE
Readme outdated, beta feedback

### ISSUE THREAD

**Issue by xblox** [dojo/cli-create-app#68]
Hi,
just for your information: following the beta announcement on Twitter, I installed as described in the Readme.md :

```
npm install -g @dojo/cli-create-app (installing @dojo/cli 2.0.0-beta1.1)
dojo create app -n test
cd test
grunt dev
```
which gives me : `Warning: Task "dev" not found` and after checking: there is indeed no Gruntfile.js!

I realized then, its actually: `dojo test` or `dojo build`

The other confusing parts are: 

- no idea what `dojo build` does and how to influence it
- server-side rendering entirely unclear
- pure server apps and/or isomorphic code also unclear
- no idea how to deal with auto-compile after save via ts-node or similar

I can make a PR to update _Readme.md_ files, other packages seem also to have misleading/confusing/outdated text, leaving many many questions open.

greets & congrats for beta-1, waited 3 years for this,
guenter

**Comment by xblox** [comment]
weird: npm install -g @dojo/cli-create-app on a windows box doesn't make the dojo command available, win-10,x64 with node-v-7.7.3 and no excotic shell stuff installed.
g

**Comment by agubler** [comment]
@xblox Thanks for the feedback. The instructions to use `grunt` are for if you are working with the source and is under the "How do I contribute?" section of the README, which states the first you need to clone the repository.

I have raised a PR that gives more information about how to use the skeleton project #69, hopefully that will help resolve confusion.

> no idea what dojo build does and how to influence it

`dojo build` is the `@dojo/cli` command for building Dojo 2 applications which uses webpack internally. The command is intentionally "no config" with intelligent defaults, however if there is a  need to customise the webpack configuration then advanced users can use `dojo eject` to remove themselves from the `@dojo/cli` ecosystem (note: this action is not reversible).

> server-side rendering entirely unclear
> pure server apps and/or isomorphic code also unclear

These capabilities are not provided with the current project skeleton, with SSR and Server Apps being something that we will be working towards through the betas and beyond.

> no idea how to deal with auto-compile after save via ts-node or similar

If you mean a watch? You can use `dojo build --watch` that will automatically rebuild the application when a file change is detected and also serves the build on port `9999` (by default).

> weird: npm install -g @dojo/cli-create-app on a windows box doesn't make the dojo command available, win-10,x64 with node-v-7.7.3 and no excotic shell stuff installed.

Thanks for this, we'll look into this.

**Comment by agubler** [comment]
I just installed `@dojo/cli` globally on windows 10 x64 (node 6) and the `create` command was available. I also tested with a `dojo create -n test` and then `dojo build -w` in the project which was successful.

You shouldn't need to install the command globally anymore as it's bundled with the `cli` (I'll update the readme for that also).

**Comment by xblox** [comment]
hi, thanks a lot. now this makes sense. no idea why my winbox can't find 'dojo' but ok, that might be some OS problem. 
closing this.g
