### ISSUE TITLE
Change app CSS file to be plain css rather than stylus

### ISSUE THREAD

**Issue by rishson** [dojo/cli-create-app#7]
Given this is the first interaction a new user will have with Dojo 2, I don't think we should presume that they know and/or are comfortable writing stylus.
I think we should create `app.css` and include some basic styles in plain old CSS.

**Comment by kitsonk** [comment]
Will this give good coverage of browser specific prefixes?  Isn't having to do all that a poor developer experience?  Does not having a pre-processor actually make it a good thing allowing an developer write better CSS?  Just like us using TypeScript allows them to write better JavaScript?

Refs dojo/meta#30, though obviously what we use to build maintainable internal styles does not have to be what we hoist onto others.

**Comment by rishson** [comment]
For the 'hello world' app that `cli` creates, I'd say just a couple of simple pure CSS styles is sufficient and does not presume anything of the user.

Going forward:

```
dojo config set css=stylus
dojo create myNewStylusApp
```

could work, if they wanted to change the default CSS format to something else. We would then pull in `dojo-cli-stylus` during the `build` step.

**Comment by kitsonk** [comment]
Sounds like a reasonable solution, IMO.

**Comment by agubler** [comment]
Conceptually seems reasonable to use global config as a way of instructing commands of your preferences. Config is certainly something that we have always discussed to support various capabilities in the future (like default command for a group etc).

Perhaps we wouldn't have a command per se for a style preprocessor, but certainly all the commands that care could/would use the config to determine the template to add in create app and the preprocessor required in build etc etc.

**Comment by tomdye** [comment]
This will likely be closed as part of https://github.com/dojo/cli-create-app/issues/33

**Comment by tomdye** [comment]
Addressed by https://github.com/dojo/cli-create-app/issues/33
