### ISSUE TITLE
Support creating more than one app

### ISSUE THREAD

**Issue by rishson** [dojo/cli-create-app#71]
# Problem
We have created several tutorials based on the code produced by `dojo create` `alpha.11`.
Now that the boilerplate produced is out of step with the tutorials, we can either update all the tutorials to match the latest boilerplate, or we can introduce a way to produce different types of boilerplate.
The drawback with updating the tutorials, is that the generated is always a moving target and so this activity may have to be undertaken many times.

**Comment by rishson** [comment]
# Proposal
In order to break the link between the initial tutorials and the boilerplate generated by `dojo create`, we could support creating multiple boilerplates from this command, `dojo create tutorial1`, `dojo create -t tutorial1` or similar.
I propose:

- creating a `templates` subdir
- underneath `templates`, each subfolder will contain a command that creates specific boilerplate, e.g. `/templates/tutorial1` will create the boilerplate for the first set of tutorials.
- `dojo create -h` will enumerate the `templates` dir and list out the available types of `create` available.
- we should keep default behaviour unchanged, e.g. `dojo create -n` will create the existing boilerplate`
- we should move the existing template files to `/templates/__default`

Thoughts, opinions..

**Comment by kitsonk** [comment]
I think this is very germane to PRs #86 and #85 in the sense that with a _basic_ app I wouldn't expect certain features to be scaffolded, even if they are a noop.  Even noops can have build impacts, etc... let alone be confusing to the developer.  Where as having a _PWA_ scaffold would do that in a slightly different way and feel natural.

**Comment by kitsonk** [comment]
We discussed this in the 03 August design meeting.  I believe we agreed that:

* Unique scaffolds should be kept to a minimum.
* That _options_ for a scaffold, like if the application is a PWA app, should be contained in the `.dojorc`.

This is related to dojo/cli#158.

**Comment by agubler** [comment]
We now support 2 different templates 1) a skeleton application 2) a demo application using dojo/widgets, routing and code splitting ootb.

Both of these templates are available in TSX
