### ISSUE TITLE
API Doc Review for cli-create-app

### ISSUE THREAD

**Issue by eheasley** [dojo/cli-create-app#72]
Review the generated API documentation for `cli-create-app` at http://dojo.io/api/. If any of the information is not accurate, please make the necessary adjustments to the API documentation within this repo.

**Comment by dylans** [comment]
We determined that docs for cli do not belong in the API list, and thus they have been removed.

There is value in documenting the end-user usage, but we cannot generated that automatically.

So I think this issue should be closed.
