### ISSUE TITLE
Error occurs creating a new application

### ISSUE THREAD

**Issue by agubler** [dojo/cli-create-app#81]
**Bug**

An error occurs when running `dojo create -n my-app`.

```
⠋ npm install(node:41307) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOENT: no such file or directory, open '....../.nvm/versions/node/v6.9.1/lib/node_modules/@dojo/cli/node_modules/@dojo/cli-create-app/templates/.gitignore'
```
It does not prevent the command from completing.

**Comment by lzhoucs** [comment]
It seems the published package in the public npm registry doesn't contain `templates/.gitignore` file, whereas this file does exist in the `dist/umd` if I run `grunt dist` or `grunt release --dry-run`. I am not exactly sure how we published this package, but [`dot: true`](https://github.com/dojo/cli-create-app/blob/master/Gruntfile.js#L25) has to be included in the grunt option during the publish process for the hidden files to be copied over to the `dist/umd` folder.

**Comment by agubler** [comment]
Thanks @lzhoucs for the investigation.
